iterations: null
learning_rate: null
depth: null
l2_leaf_reg: null
model_size_reg: null
rsm: null
loss_function: "RMSE"
border_count: null
feature_border_type: null
per_float_feature_quantization: null
input_borders: null
output_borders: null
fold_permutation_block: null
od_pval: null
od_wait: null
od_type: null
nan_mode: null
counter_calc_method: null
leaf_estimation_iterations: null
leaf_estimation_method: null
thread_count: null
random_seed: null
use_best_model: null
best_model_min_trees: null
verbose: null
silent: null
logging_level: null
metric_period: null
ctr_leaf_count_limit: null
store_all_simple_ctr: null
max_ctr_complexity: null
has_time: null
allow_const_label: null
target_border: null
one_hot_max_size: null
random_strength: null
random_score_type: null
name: null
ignored_features: null
train_dir: null
custom_metric: null
eval_metric: null
bagging_temperature: null
save_snapshot: null
snapshot_file: null
snapshot_interval: null
fold_len_multiplier: null
used_ram_limit: null
gpu_ram_part: null
pinned_memory_size: null
allow_writing_files: null
final_ctr_computation_mode: null
approx_on_full_history: null
boosting_type: null
simple_ctr: null
combinations_ctr: null
per_feature_ctr: null
ctr_description: null
ctr_target_border_count: null
task_type: null
device_config: null
devices: null
bootstrap_type: null
subsample: null
mvs_reg: null
sampling_frequency: null
sampling_unit: null
dev_score_calc_obj_block_size: null
dev_efb_max_buckets: null
sparse_features_conflict_fraction: null
max_depth: null
n_estimators: null
num_boost_round: null
num_trees: null
colsample_bylevel: null
random_state: null
reg_lambda: null
objective: null
eta: null
max_bin: null
gpu_cat_features_storage: null
data_partition: null
metadata: null
early_stopping_rounds: null
cat_features: null
grow_policy: null
min_data_in_leaf: null
min_child_samples: null
max_leaves: null
num_leaves: null
score_function: null
leaf_estimation_backtracking: null
ctr_history_unit: null
monotone_constraints: null
feature_weights: null
penalties_coefficient: null
first_feature_use_penalties: null
per_object_feature_penalties: null
model_shrink_rate: null
model_shrink_mode: null
langevin: null
diffusion_temperature: null
posterior_sampling: null
boost_from_average: null
text_features: null
tokenizers: null
dictionaries: null
feature_calcers: null
text_processing: null
embedding_features: null
eval_fraction: null
fixed_binary_splits: null
