defaults:
  - data: dataset
  - preprocess: catboost
  - model: mlp
  - train: default
  - mlflow: local
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    env_set:
      TOKENIZERS_PARALLELISM: false
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_TRACKING_URI: http://localhost:5000
      MLFLOW_S3_ENDPOINT_URL: http://localhost:9000
